const STORIES = [
 {id:0,title:'In the Beginning',short:'Creation',icon:'🌍',ref:'Genesis 1:1',verse:'In the beginning God created the heaven and the earth.',context:'Scripture opens with God already present. Creation is His purposeful work, and everything He made was declared good.',preview:'Light breaks into the darkness, and creation begins.',tiles:['🌍|Earth','☀️|Light','🌙|Night','⭐|Stars','🌊|Waters','🌿|Plants'],accent:'#bdd9c5'},
 {id:1,title:'Sky, Sea & Land',short:'Creation',icon:'🌅',ref:'Genesis 1:10',verse:'And God called the dry land Earth; and the gathering together of the waters called he Seas: and God saw that it was good.',context:'God brings order and abundance to what was formless. The repeated phrase “it was good” shows the goodness of His design.',preview:'The empty world begins to fill with life.',tiles:['🌅|Sky','🌊|Sea','⛰️|Land','🌳|Tree','🌸|Flower','☁️|Cloud'],accent:'#b8d8dc'},
 {id:2,title:'Creatures Great & Small',short:'Creation',icon:'🐋',ref:'Genesis 1:21',verse:'And God created great whales, and every living creature that moveth ... and God saw that it was good.',context:'Life fills the seas, skies, and land. Every creature depends upon the Creator and displays His imagination.',preview:'God prepares to create humanity in His image.',tiles:['🐋|Whale','🐦|Bird','🦁|Lion','🐑|Sheep','🐟|Fish','🦋|Butterfly'],accent:'#c8dcb2'},
 {id:3,title:'Made in His Image',short:'Adam & Eve',icon:'👫',ref:'Genesis 1:27',verse:'So God created man in his own image, in the image of God created he him; male and female created he them.',context:'Human dignity begins here: both man and woman bear God’s image. They are given the calling to care for creation under His authority.',preview:'A beautiful garden holds both provision and a command.',tiles:['👫|People','🌍|Earth','👑|Image','👐|Care','🌿|Garden','✨|Blessing'],accent:'#e5c89e'},
 {id:4,title:'The Garden of Eden',short:'Eden',icon:'🌳',ref:'Genesis 2:15',verse:'And the LORD God took the man, and put him into the garden of Eden to dress it and to keep it.',context:'Work existed before sin and was part of God’s good design. Adam receives both generous provision and a clear boundary.',preview:'The serpent questions God’s good word.',tiles:['🌳|Garden','🍎|Fruit','🌱|Life','💧|River','🦜|Creature','🌺|Beauty'],accent:'#b9d8a4'},
 {id:5,title:'The Fall',short:'The Fall',icon:'🍂',ref:'Genesis 3:15',verse:'And I will put enmity between thee and the woman, and between thy seed and her seed.',context:'Human rebellion brings shame, separation, and death. Yet within God’s judgment is the first promise that evil will ultimately be defeated.',preview:'Outside Eden, sin spreads—but God still shows mercy.',tiles:['🐍|Serpent','🍎|Fruit','🍂|Fall','🚪|Exile','🧥|Covering','🌅|Promise'],accent:'#d5b19d'},
 {id:6,title:'Cain and Abel',short:'Two Brothers',icon:'🌾',ref:'Genesis 4:7',verse:'If thou doest well, shalt thou not be accepted? and if thou doest not well, sin lieth at the door.',context:'God warns Cain before his anger becomes violence. The account shows both the seriousness of sin and God’s pursuit of the sinner.',preview:'Generations pass and violence fills the earth.',tiles:['🌾|Offering','🐑|Flock','🔥|Altar','🚪|Warning','💔|Anger','🛡️|Mercy'],accent:'#d9c795'},
 {id:7,title:'Noah Walked with God',short:'Noah',icon:'🧔',ref:'Genesis 6:9',verse:'Noah was a just man and perfect in his generations, and Noah walked with God.',context:'Noah is not presented as sinless, but as one who trusted God amid a corrupt generation. His faith becomes visible through obedience.',preview:'God gives Noah an enormous and unusual assignment.',tiles:['🧔|Noah','👣|Walk','🙏|Faith','🌍|World','🌧️|Warning','✨|Favor'],accent:'#b8cbd1'},
 {id:8,title:'Build the Ark',short:'The Ark',icon:'🔨',ref:'Genesis 6:22',verse:'Thus did Noah; according to all that God commanded him, so did he.',context:'The ark story emphasizes careful obedience. Noah acts on God’s warning long before the rain begins.',preview:'The animals begin arriving—two by two.',tiles:['🔨|Hammer','🪵|Wood','📐|Measure','🚢|Ark','🚪|Door','🙏|Obey'],accent:'#d5b07f'},
 {id:9,title:'Two by Two',short:'The Animals',icon:'🦒',ref:'Genesis 7:9',verse:'There went in two and two unto Noah into the ark, the male and the female, as God had commanded Noah.',context:'God preserves animal life through the ark. The scene shows His authority over creation and faithfulness to His word.',preview:'The door closes, and the rain finally begins.',tiles:['🦒|Giraffe','🐘|Elephant','🦁|Lion','🐦|Bird','🐑|Sheep','🚢|Ark'],accent:'#dbcf98'},
 {id:10,title:'The Flood',short:'The Flood',icon:'🌧️',ref:'Genesis 7:17',verse:'And the flood was forty days upon the earth; and the waters increased, and bare up the ark.',context:'The flood is both judgment on human violence and preservation through God’s provision. God remembers Noah and those with him.',preview:'The waters recede. Noah waits for a sign of dry land.',tiles:['🌧️|Rain','🌊|Water','🚢|Ark','🕊️|Dove','🌿|Leaf','⛰️|Mountain'],accent:'#aebfcb'},
 {id:11,title:'The Rainbow Covenant',short:'God’s Promise',icon:'🌈',ref:'Genesis 9:13',verse:'I do set my bow in the cloud, and it shall be for a token of a covenant between me and the earth.',context:'The rainbow is God’s covenant sign. It reminds every generation of His mercy and His promise concerning the earth.',preview:'People spread across the earth, and the journey toward Abraham begins.',tiles:['🌈|Rainbow','☁️|Cloud','🕊️|Peace','🌍|Earth','🤝|Covenant','✨|Promise'],accent:'#e2c7dd'}
];

const LAYOUTS = [
 [[0,1,0],[2,1,0],[4,1,0],[1,2,0],[3,2,0],[0,3,0],[2,3,0],[4,3,0],[1,4,0],[3,4,0],[0,5,0],[2,5,0],[4,5,0],[1,6,0],[3,6,0],[2,2,1],[2,4,1],[2,3,2]],
 [[1,0,0],[3,0,0],[0,1,0],[2,1,0],[4,1,0],[0,3,0],[2,3,0],[4,3,0],[1,4,0],[3,4,0],[0,5,0],[2,5,0],[4,5,0],[1,6,0],[3,6,0],[1,2,1],[3,2,1],[2,2,2]],
 [[0,1,0],[2,1,0],[4,1,0],[0,3,0],[2,3,0],[4,3,0],[0,5,0],[2,5,0],[4,5,0],[1,2,0],[3,2,0],[1,4,0],[3,4,0],[1,6,0],[3,6,0],[2,2,1],[2,4,1],[2,3,2]]
];

const defaults={unlocked:0,completed:{},stars:{},collection:[],games:0,matches:0,streak:1,lastDay:'',sound:true,tools:{hint:3,shuffle:3,remove:2}};
let save=loadSave(), screen='home', game=null, toastTimer;
function loadSave(){try{return {...defaults,...JSON.parse(localStorage.getItem('bj-save')||'{}')}}catch{return {...defaults}}}
function persist(){localStorage.setItem('bj-save',JSON.stringify(save))}
function today(){return new Date().toISOString().slice(0,10)}
function h(tag,cls,html){const e=document.createElement(tag);if(cls)e.className=cls;if(html!==undefined)e.innerHTML=html;return e}
function showToast(msg){document.querySelector('.toast')?.remove();const t=h('div','toast',msg);document.body.append(t);clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.remove(),2300)}
function stars(n=0){return '★'.repeat(n)+'☆'.repeat(3-n)}

function render(){const app=document.querySelector('#app');app.innerHTML='';if(screen==='game') return renderGame(app);app.append(mainShell())}
function mainShell(){const shell=h('main','shell');shell.append(topbar());const body=h('section','screen');if(screen==='home')home(body);if(screen==='journey')journey(body);if(screen==='collection')collection(body);if(screen==='profile')profile(body);shell.append(body,bottomNav());return shell}
function topbar(){const e=h('header','topbar');e.innerHTML=`<div><div class="brand">Bible Journey</div><div class="subbrand">Match & Discover</div></div><div class="pill">⭐ ${Object.values(save.stars).reduce((a,b)=>a+b,0)}</div>`;return e}
function bottomNav(){const n=h('nav','bottom-nav');[['home','⌂','Home'],['journey','🗺️','Journey'],['collection','📖','Collection'],['profile','👤','My Path']].forEach(([id,ico,label])=>{const b=h('button','nav-btn '+(screen===id?'active':''),`<span>${ico}</span>${label}`);b.onclick=()=>{screen=id;render()};n.append(b)});return n}

function home(b){const next=STORIES[Math.min(save.unlocked,STORIES.length-1)];const done=Object.keys(save.completed).length;b.innerHTML=`<div class="hero"><div class="eyebrow">Your journey continues</div><h1>${next.title}</h1><p>${next.preview}</p><button class="primary" id="continue">${done?'Continue journey':'Begin the journey'}</button></div>`;
 b.querySelector('#continue').onclick=()=>startLevel(next.id);
 const title=h('h2','section-title','Today’s Journey');b.append(title);const d=h('div','journey-card daily',`<div class="chapter-icon">☀️</div><div style="flex:1"><div class="eyebrow" style="color:#8d6924">Daily board</div><h3>${save.lastDay===today()?'Completed today':'A new moment of peace'}</h3><p>${save.lastDay===today()?'Return tomorrow for a new board.':'Match, reflect, and collect today’s reward.'}</p></div>`);d.onclick=()=>startLevel(new Date().getDate()%Math.max(1,save.unlocked+1),true);b.append(d);
 const t=h('h2','section-title','Journey progress');b.append(t);const p=h('div','card');p.innerHTML=`<div style="display:flex;justify-content:space-between"><b>Creation to New Creation</b><span>${done}/${STORIES.length}</span></div><div class="progress"><i style="width:${done/STORIES.length*100}%"></i></div>`;b.append(p);
 b.append(levelCard(next));
}
function levelCard(s){const c=h('div','journey-card',`<div class="chapter-icon" style="background:${s.accent}">${s.icon}</div><div style="flex:1"><h3>${s.id+1}. ${s.title}</h3><p>${s.ref} · ${save.completed[s.id]?'Complete':'Next story'}</p><div class="stars">${stars(save.stars[s.id]||0)}</div></div><b>›</b>`);c.onclick=()=>startLevel(s.id);return c}
function journey(b){b.innerHTML='<h1 class="section-title" style="margin-top:4px">The Bible Journey</h1><p style="color:var(--muted)">Restore each scene and discover the story of redemption.</p>';STORIES.forEach((s,i)=>{const c=levelCard(s);if(i>save.unlocked){c.classList.add('locked');c.onclick=()=>showToast('Complete the earlier story first')};b.append(c)});const future=h('div','journey-card locked',`<div class="chapter-icon">⭐</div><div><h3>Coming next: Abraham</h3><p>God calls one family to bless all nations.</p></div>`);b.append(future)}
function collection(b){b.innerHTML=`<h1 class="section-title" style="margin-top:4px">Discovery Book</h1><p style="color:var(--muted)">${save.collection.length} of ${STORIES.length} story cards discovered</p>`;const g=h('div','collection-grid');STORIES.forEach(s=>{const unlocked=save.collection.includes(s.id);const c=h('div','collect '+(!unlocked?'locked-card':''),`<div class="art">${unlocked?s.icon:'?'}</div><h4>${unlocked?s.title:'Undiscovered'}</h4><small>${unlocked?s.ref:'Complete its story'}</small>`);if(unlocked)c.onclick=()=>storyModal(s,false);g.append(c)});b.append(g)}
function profile(b){const totalStars=Object.values(save.stars).reduce((a,v)=>a+v,0);b.innerHTML=`<h1 class="section-title" style="margin-top:4px">My Bible Path</h1><div class="stat-grid"><div class="card stat"><strong>${Object.keys(save.completed).length}</strong><span>Stories</span></div><div class="card stat"><strong>${totalStars}</strong><span>Stars</span></div><div class="card stat"><strong>${save.matches}</strong><span>Matches</span></div><div class="card stat"><strong>${save.streak}</strong><span>Day streak</span></div></div><h2 class="section-title">Settings</h2><div class="card"><div class="settings-row"><span>🔊 Gentle sounds</span><button id="sound" class="switch ${save.sound?'on':''}"><i></i></button></div><div class="settings-row"><span>📱 Install on Android</span><button id="install" class="secondary" style="padding:8px 12px">How</button></div><div class="settings-row" style="border:0"><span>↻ Reset progress</span><button id="reset" class="secondary" style="padding:8px 12px;color:var(--rose)">Reset</button></div></div><div class="card"><div class="eyebrow" style="color:#8d6924">Today’s thought</div><p class="verse" style="font-family:Georgia,serif;line-height:1.5">“Thy word is a lamp unto my feet, and a light unto my path.”</p><small>Psalm 119:105</small></div>`;
 b.querySelector('#sound').onclick=()=>{save.sound=!save.sound;persist();render()};b.querySelector('#install').onclick=()=>infoModal('Install on Android','Open the published game in Chrome, tap the ⋮ menu, then choose <b>Install app</b> or <b>Add to Home screen</b>. The game will open full-screen and work offline.');b.querySelector('#reset').onclick=()=>{if(confirm('Reset all journey progress? This cannot be undone.')){save={...defaults,completed:{},stars:{},collection:[],tools:{...defaults.tools}};persist();render()}}}

function makeDeck(story,level){const layout=LAYOUTS[level%LAYOUTS.length];const pairCount=layout.length/2;let values=[];for(let i=0;i<pairCount;i++){const val=story.tiles[i%story.tiles.length];values.push(val,val)};shuffle(values);return layout.map((p,i)=>({id:i,x:p[0],y:p[1],z:p[2],value:values[i],removed:false}))}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function startLevel(id,daily=false){if(id>save.unlocked)return;const s=STORIES[id];game={id,daily,story:s,tiles:makeDeck(s,id),selected:null,moves:0,undos:[],started:Date.now(),usedShuffle:false};screen='game';render()}
function isFree(t){if(t.removed)return false;const above=game.tiles.some(o=>!o.removed&&o.z>t.z&&Math.abs(o.x-t.x)<1.1&&Math.abs(o.y-t.y)<1.1);if(above)return false;const left=game.tiles.some(o=>!o.removed&&o.z===t.z&&o.x<t.x&&Math.abs(o.x-t.x)<=2.1&&Math.abs(o.y-t.y)<.6);const right=game.tiles.some(o=>!o.removed&&o.z===t.z&&o.x>t.x&&Math.abs(o.x-t.x)<=2.1&&Math.abs(o.y-t.y)<.6);return !(left&&right)}
function availablePairs(){const free=game.tiles.filter(isFree);const pairs=[];for(let i=0;i<free.length;i++)for(let j=i+1;j<free.length;j++)if(free[i].value===free[j].value)pairs.push([free[i],free[j]]);return pairs}
function renderGame(app){const root=h('main','game-shell');root.innerHTML=`<header class="game-head"><button class="back">‹</button><div><div class="game-title">${game.story.title}</div><div class="game-sub">${game.story.ref}</div></div><button class="round-btn">☰</button></header><div class="objective">Match two open tiles · ${game.tiles.filter(t=>!t.removed).length} remaining</div>`;root.querySelector('.back').onclick=exitGame;root.querySelector('.round-btn').onclick=()=>infoModal('Pause','Your board is saved while this screen is open.<br><br><button class="primary" onclick="document.querySelector(\'.modal-bg\').remove()">Keep playing</button>');
 const wrap=h('div','board-wrap');const board=h('div','board');const maxZ=Math.max(...game.tiles.map(t=>t.z));game.tiles.forEach(t=>{const tile=h('button','tile');const [sym,label]=t.value.split('|');tile.innerHTML=`<span class="symbol">${sym}</span><span class="label">${label}</span>`;tile.style.left=`${3+t.x*19}%`;tile.style.top=`${2+t.y*12.5}%`;tile.style.zIndex=t.z*10+t.id;tile.style.transform=`translate(${t.z*3}px,${-t.z*4}px)`;if(t.removed)tile.classList.add('matched');if(!isFree(t))tile.classList.add('blocked');if(game.selected===t.id)tile.classList.add('selected');tile.onclick=()=>tapTile(t);board.append(tile)});wrap.append(board);root.append(wrap);
 const tools=h('div','game-tools');[['hint','💡','Hint'],['shuffle','🔀','Shuffle'],['undo','↶','Undo'],['remove','🕊️','Pair']].forEach(([id,ico,label])=>{const count=id==='undo'?'':`<small>${save.tools[id]??''}</small>`;const btn=h('button','tool',`${count}<b>${ico}</b>${label}`);btn.onclick=()=>useTool(id);tools.append(btn)});root.append(tools);app.append(root)}
function tapTile(t){if(!isFree(t)){showToast('That tile is still blocked');return}if(game.selected===null){game.selected=t.id;playTone(500);render();return}if(game.selected===t.id){game.selected=null;render();return}const first=game.tiles.find(x=>x.id===game.selected);game.moves++;if(first.value===t.value){first.removed=t.removed=true;game.undos.push([first.id,t.id]);game.selected=null;save.matches++;playTone(760);persist();if(game.tiles.every(x=>x.removed)){setTimeout(levelComplete,250);return}if(!availablePairs().length)setTimeout(()=>{showToast('No open matches—tiles reshuffled');shuffleRemaining()},350)}else{game.selected=t.id;playTone(290);showToast('Try another matching symbol')}render()}
function shuffleRemaining(){const live=game.tiles.filter(t=>!t.removed);const vals=live.map(t=>t.value);shuffle(vals);live.forEach((t,i)=>t.value=vals[i]);game.usedShuffle=true;game.selected=null;render()}
function useTool(type){if(type==='undo'){const last=game.undos.pop();if(!last)return showToast('Nothing to undo');last.forEach(id=>game.tiles.find(t=>t.id===id).removed=false);game.selected=null;render();return}if((save.tools[type]||0)<=0)return showToast('Earn more by completing stories');if(type==='hint'){const p=availablePairs()[0];if(!p)return showToast('No open pair—try shuffle');game.selected=p[0].id;showToast(`Find the other ${p[0].value.split('|')[1]} tile`)}if(type==='shuffle')shuffleRemaining();if(type==='remove'){const p=availablePairs()[0];if(!p)return showToast('No open pair to remove');p.forEach(t=>t.removed=true);game.undos.push(p.map(t=>t.id));if(game.tiles.every(x=>x.removed))setTimeout(levelComplete,250)}save.tools[type]--;persist();render()}
function levelComplete(){const elapsed=(Date.now()-game.started)/1000;let earned=3;if(game.usedShuffle||game.moves>15)earned=2;if(game.moves>22)earned=1;save.games++;save.completed[game.id]=true;save.stars[game.id]=Math.max(save.stars[game.id]||0,earned);if(!save.collection.includes(game.id))save.collection.push(game.id);save.unlocked=Math.min(STORIES.length-1,Math.max(save.unlocked,game.id+1));if(game.daily){if(save.lastDay!==today())save.streak++;save.lastDay=today()}if(save.games%3===0)save.tools.hint++;persist();storyModal(game.story,true,earned)}
function storyModal(s,completed=false,earned=0){const bg=h('div','modal-bg');const m=h('div','modal');m.innerHTML=`<div class="big-icon">${s.icon}</div>${completed?`<div class="reward-stars">${stars(earned)}</div>`:''}<div class="eyebrow" style="color:#8d6924">${completed?'Story discovered':'Discovery card'}</div><h2>${s.title}</h2><div class="verse">“${s.verse}”<br><small>— ${s.ref} (KJV)</small></div><p class="context">${s.context}</p><p style="font-weight:700;color:var(--forest)">${s.preview}</p><div class="modal-actions"><button class="secondary" id="map">Journey map</button>${completed?'<button class="primary" id="next">Next story</button>':'<button class="primary" id="close">Close</button>'}</div>`;bg.append(m);document.body.append(bg);m.querySelector('#map').onclick=()=>{bg.remove();screen='journey';game=null;render()};m.querySelector('#close')?.addEventListener('click',()=>bg.remove());m.querySelector('#next')?.addEventListener('click',()=>{bg.remove();const next=Math.min(s.id+1,STORIES.length-1);game=null;startLevel(next)});}
function infoModal(title,copy){const bg=h('div','modal-bg');const m=h('div','modal');m.innerHTML=`<div class="big-icon">📖</div><h2>${title}</h2><p class="context">${copy}</p><button class="primary" id="ok" style="width:100%">Got it</button>`;bg.append(m);document.body.append(bg);m.querySelector('#ok').onclick=()=>bg.remove();bg.onclick=e=>{if(e.target===bg)bg.remove()}}
function exitGame(){if(confirm('Return to the journey map?')){game=null;screen='journey';render()}}
function playTone(freq){if(!save.sound)return;try{const c=new (window.AudioContext||window.webkitAudioContext)();const o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.05,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.12);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.13)}catch{}}
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
render();
